### ISSUE TITLE
Doesn't build under Linux

### ISSUE THREAD

**Issue by mahboi** [PistonMiner/TF2Classic#10]
When I try to build this mod on Linux using the the instructions for the Source SDK Base 2013 on Linux on the Valve Developer Community, I get the error "<command-line>:0:1: error: macro names must be identifiers" when make tries to build a few files. I've tried to investigate the problem myself, but I have found nothing helpful.

Here's my make output:

`matthew@localhost:~/Projects/TF2Classic/src$ make -f Tf2Classic.mak`
`make -f Tf2Classic.mak -j4 all-targets`
`make[1]: Entering directory '/home/matthew/Projects/TF2Classic/src'`
`Building: mathlib`
`Building: tier1`
`Building: vgui_controls`
`Building: raytrace`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/vgui2/vgui_controls'`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/tier1'`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/mathlib'`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/raytrace'`
`make[2]: Leaving directory '/home/matthew/Projects/TF2Classic/src/mathlib'`
`make[2]: Leaving directory '/home/matthew/Projects/TF2Classic/src/raytrace'`
`make[2]: Leaving directory '/home/matthew/Projects/TF2Classic/src/tier1'`
`Building: server_tf`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/game/server'`
`make[2]: Leaving directory '/home/matthew/Projects/TF2Classic/src/vgui2/vgui_controls'`
`Building: client_tf`
`make[2]: Entering directory '/home/matthew/Projects/TF2Classic/src/game/client'`
`---- language.cpp ----`
`---- randoverride.cpp ----`
`---- serverbenchmark_base.cpp ----`
`<command-line>:0:1: error: macro names must be identifiers`
`<command-line>:0:1: error: macro names must be identifiers`
`server_linux32_tf2classic.mak:663: recipe for target 'obj_server_tf_linux32/release/language.o' failed`
`make[2]: *** [obj_server_tf_linux32/release/language.o] Error 1`
`make[2]: *** Waiting for unfinished jobs....`
`server_linux32_tf2classic.mak:667: recipe for target 'obj_server_tf_linux32/release/randoverride.o' failed`
`make[2]: *** [obj_server_tf_linux32/release/randoverride.o] Error 1`
`<command-line>:0:1: error: macro names must be identifiers`
`---- LINKING obj_client_tf_linux32/release/client.so [release] ----`
`server_linux32_tf2classic.mak:671: recipe for target` `'obj_server_tf_linux32/release/serverbenchmark_base.o' failed`
`make[2]: *** [obj_server_tf_linux32/release/serverbenchmark_base.o] Error 1`
`make[2]: Leaving directory '/home/matthew/Projects/TF2Classic/src/game/server'`
`Tf2Classic.mak:48: recipe for target 'server_tf' failed`
`make[1]: *** [server_tf] Error 2`
`make[1]: *** Waiting for unfinished jobs....`

**Comment by NicknineTheEagle** [comment]
The code in this repository is horribly outdated at this point as such the issue report is not valid.

**Comment by mahboi** [comment]
Is the latest code private?

**Comment by NicknineTheEagle** [comment]
Yes, the code was moved to a private repository some time ago.
